library_version = "0.2"

[source]
exclude = [".git", ".ignore", ".on_commit.fish", "run", "deno.json"]

[out]
path = "docs/"
lib_file = "js/router.js"

[js]
update_anchors = false

[scripts]
prebuild = "deno bundle --outdir js ./ts/**.ts"
# ts cant be excluded cuz then it gets excluded from `dev watch`.
postbuild = "rm -rf js/ docs/ts"
