library_version = "0.2"

[source]
exclude = [".git", ".ignore", ".on_commit.fish", "run", "ts"]

[out]
path = "docs/"
lib_file = "js/router.js"

[js]
update_anchors = false

[scripts]
prebuild = "deno bundle --outdir js ./ts/**.ts"
postbuild = "rm -rf js/"
